baseurl = "http://bertvv.github.io/notes-to-self/"
languageCode = "en-us"
title = "Notes to self"
disqusShortname = "notes-to-self-bertvv"
copyright = "© 2015 Bert Van Vreckem. Some rights reserved. Please attribute properly and link back."

[author]
    name = "Bert Van Vreckem"

[indexes]
    tag = "tags"
    topic = "topics"
