baseurl = "http://bertvv.github.io/notes-to-self/"
languageCode = "en-us"
title = "Notes to self"
disqusShortname = "notes-to-self-bertvv"
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Notes to self</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://bertvv.github.io/notes-to-self/" property="cc:attributionName" rel="cc:attributionURL">Bert Van Vreckem</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.'

[author]
    name = "Bert Van Vreckem"

[indexes]
    tag = "tags"
    topic = "topics"
